### ISSUE TITLE
[DOCS] - Add issue finder link

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/general-documentation#10]
### What would you like to share?

We launched a new issue finder at https://contribute.nhcarrigan.com.

In the [top level contributing instructions](https://github.com/nhcarrigan/general-documentation/blob/main/docs/contributing.md), just below the first tip box, we should add some text which says something like `Looking for an issue to work on? Check out our [issue finder](https://contribute.nhcarrigan.com)!`. This will help people who are looking to get started.

**Comment by TAKANOME-DEV** [comment]
Oh I see, that's a good idea. I'm excited to do it 🚀

**Comment by nhcarrigan** [comment]
All yours!
